name: splunk
priority: 100
transformations:
  # Field Mapping
  - type: field_name_mapping
    mapping:
      eventtype: eventType
      email: actor.alternateId
      outcome.result: outcome.result
      city_name: client.geographicalContext.city
    rule_conditions:
      - type: logsource
        product: okta
        service: okta

  # Add the `index=okta` prefix to the fule
  - type: add_condition
    conditions:
      index: okta # here
    rule_conditions:
      - type: logsource
        product: okta
        service: okta
